### ISSUE TITLE
Slider does not respect the step value on when using with keyboard

### ISSUE THREAD

**Issue by maximilize** [callstack/react-native-slider#155]
## Environment

```
System:
    OS: Linux 4.19 Fedora 30 (Thirty) 30 (Thirty)
    CPU: (4) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 330.60 MB / 9.36 GB
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 13.8.0 - ~/.local/node-v13.8.0-linux-x64/bin/node
    npm: 6.13.6 - ~/.local/node-v13.8.0-linux-x64/bin/npm
  npmPackages:
    @react-native-community/cli: ^4.1.0 => 4.1.0 
    react: ^16.9.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5
```

## Description

When using the slider with for example a remote control or keyboard, the `step` property is ignored. This does not allow us to do fine grained sliding. On a full width slider there are maybe 16 steps.

The goal should be on a minimum value of 0, and a maximum value of 1000, and a `step` value of 1, 1000 steps.

**Comment by michalchudziak** [comment]
Hey, @maximilize  thanks for reporting! I'd appreciate any PRs fixing this issue :)

**Comment by Sharcoux** [comment]
@michalchudziak should be working on Web. https://github.com/react-native-community/react-native-slider/issues/169

**Comment by Sharcoux** [comment]
Could you confirm that the problem disappear when using @sharcoux/slider from npm ?

**Comment by BartoszKlonowski** [comment]
Hello @maximilize!
I couldn't reproduce the same issue when trying it on the emulator.
Could you check if the same issue is solved on your side using the latest version?

**Comment by vafada** [comment]
@BartoszKlonowski this is still an issue

here's a video:
![bug](https://github.com/callstack/react-native-slider/assets/285941/ac38b630-8dbf-40f9-bc97-d539cf9bf3f8)

The issue is in this line:

https://github.com/callstack/react-native-slider/blob/main/package/android/src/main/java/com/reactnativecommunity/slider/ReactSlider.java#L215-L218

because of `DEFAULT_TOTAL_STEPS = 128;`

on load `mStepCalculated = 0.234375`

so `getTotalSteps` will be `128` at initial load

calling `setMax(128)` changes the internal `mKeyProgressIncrement` to `6`

see: 

https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/widget/AbsSeekBar.java;l=586-595;drc=c8c729556d69aa27fff24e5412140563fc1527af;bpv=1;bpt=1

**Comment by BartoszKlonowski** [comment]
Hello @vafada, thank you for taking the time to reach out with this!
Let me reopen the issue. I also see the linked PR - will check pretty soon.
